### ISSUE TITLE
Keep getting   TypeError: Cannot read property 'stage' of undefined

### ISSUE THREAD

**Issue by waltermvp** [serverless-components/aws-sns-subscription#3]
when attempting `serverless` i keep getting the following. Also once i remove the component from the yaml i keep getting the same error

```
  TypeError: Cannot read property 'stage' of undefined
    at new Component (/Users/waltermvp-home/.serverless/components/registry/npm/@serverless/aws-sns-subscription@0.2.0/node_modules/@serverless/components/src/core/programatic/serverless.js:18:34)
    at new AwsSnsSubscription (/Users/waltermvp-home/.serverless/components/registry/npm/@serverless/aws-sns-subscription@0.2.0/node_modules/@serverless/aws-sns-subscription/serverless.js:16:1)
    at Template.load (/usr/local/lib/node_modules/serverless/node_modules/@serverless/core/src/Component.js:112:36)
    at async fn (/usr/local/lib/node_modules/serverless/node_modules/@serverless/template/utils.js:305:27)
    at async Promise.all (index 0)
    at async syncState (/usr/local/lib/node_modules/serverless/node_modules/@serverless/template/utils.js:329:3)
    at async Template.default (/usr/local/lib/node_modules/serverless/node_modules/@serverless/template/serverless.js:42:5)
    at async Object.runComponents (/usr/local/lib/node_modules/serverless/node_modules/@serverless/cli/src/index.js:115:17)

```

**Comment by eahefnawy** [comment]
@laardee any idea what's going on here? 🤔

**Comment by laardee** [comment]
I think this component is not yet upgraded to use serverless/core 1.0. I can check this later today or tomorrow.

**Comment by laardee** [comment]
@eahefnawy This [PR](https://github.com/serverless-components/aws-sns-subscription/pull/4) will update the component to use `@serverless/core`. I opened similar [PR](https://github.com/serverless-components/aws-sns-topic/pull/2) to SNS Topic component also.
